"""
two bugs fixed, see the comments in line 15 and in line 28

This code tries to decrypt an output generated by encrypt() of encrypt_for_decrypt_2.py.

Find and fix the bug(s)!

Author: Omer Rosenbaum
"""
SECRET = "12,Vswiw$evi$vih0$Zmspixw$evi$fpyi0$Epp$q}$fewi0$Evi$fipsrk$xs$}sy"
#SECRET = "30,V4r-rq-|zruv{t-ryr;;;"

def decrypt(encrypted):
    (offset, encrypted_string) = encrypted.split(',')
    offset = (int(offset)-4)//2 # Corrected: the offset calculation was wrong, division went first
    decrypted_string =""
    for character in list(encrypted_string):
        new_value = ord(character) - offset
        new_char = chr(new_value)
        decrypted_string += new_char #instead of replasing char in a string, it's more clear to form new string
    return decrypted_string

if __name__ == "__main__":
    print(decrypt(SECRET))
